user.role.*.third_party.role_menu:
  type: role_menu.third_party_settings

role_menu.third_party_settings:
  type: mapping
  label: 'Per-role role menu settings'
  mapping:
    menu:
      type: string
      label: 'Menu'
