config_rewrite: replace
langcode: en
status: true
dependencies:
  module:
    - commerce_price
    - commerce_recurring
    - options
    - user
id: commerce_user_subscriptions
label: 'Commerce User Subscriptions'
module: views
description: 'Display a list of subscriptions for a user.'
tag: 'Commerce Recurring'
base_table: commerce_subscription
base_field: subscription_id
core: 8.x
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 0
    display_options:
      access:
        type: perm
        options:
          perm: 'administer commerce_subscription'
      cache:
        type: tag
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: false
          distinct: true
          replica: false
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: full
        options:
          items_per_page: 20
          offset: 0
          id: 0
          total_pages: null
          tags:
            previous: ‹‹
            next: ››
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          quantity: 9
      style:
        type: table
        options:
          grouping: {  }
          row_class: ''
          default_row_class: true
          override: true
          sticky: false
          caption: ''
          summary: ''
          description: ''
          columns:
            subscription_id: subscription_id
            title: title
            created: created
            starts: starts
            renewed: renewed
            unit_price__number: unit_price__number
          info:
            subscription_id:
              sortable: false
              default_sort_order: asc
              align: views-align-left
              separator: ''
              empty_column: false
              responsive: ''
            title:
              sortable: false
              default_sort_order: asc
              align: views-align-left
              separator: ''
              empty_column: false
              responsive: ''
            created:
              sortable: true
              default_sort_order: desc
              align: views-align-left
              separator: ''
              empty_column: false
              responsive: ''
            starts:
              sortable: false
              default_sort_order: asc
              align: views-align-left
              separator: ''
              empty_column: false
              responsive: ''
            renewed:
              sortable: false
              default_sort_order: asc
              align: views-align-left
              separator: ''
              empty_column: false
              responsive: ''
            unit_price__number:
              sortable: false
              default_sort_order: asc
              align: views-align-left
              separator: ''
              empty_column: false
              responsive: ''
          default: created
          empty_table: false
      row:
        type: fields
        options:
          inline: {  }
          separator: ''
          hide_empty: false
          default_field_elements: true
      fields:
        subscription_id:
          id: subscription_id
          table: commerce_subscription
          field: subscription_id
          relationship: none
          group_type: group
          admin_label: ''
          label: ID
          exclude: false
          alter:
            alter_text: false
          element_class: ''
          element_default_classes: false
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: number_integer
          settings:
            thousand_separator: ','
            prefix_suffix: false
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          entity_type: commerce_subscription
          entity_field: subscription_id
          plugin_id: field
        initial_order:
          id: initial_order
          table: commerce_subscription
          field: initial_order
          relationship: none
          group_type: group
          admin_label: ''
          label: 'Initial order'
          exclude: false
          alter:
            alter_text: false
          element_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: target_id
          type: entity_reference_label
          settings:
            link: true
          group_column: target_id
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          entity_type: commerce_subscription
          entity_field: initial_order
          plugin_id: field
        title:
          id: title
          table: commerce_subscription
          field: title
          relationship: none
          group_type: group
          admin_label: ''
          label: Title
          exclude: false
          alter:
            alter_text: false
          element_class: ''
          element_default_classes: false
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          settings:
            link_to_entity: false
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          entity_type: commerce_subscription
          entity_field: title
          plugin_id: field
        billing_schedule:
          id: billing_schedule
          table: commerce_subscription
          field: billing_schedule
          relationship: none
          group_type: group
          admin_label: ''
          label: 'Billing schedule'
          exclude: false
          alter:
            alter_text: false
          element_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: target_id
          type: entity_reference_label
          settings:
            link: true
          group_column: target_id
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          entity_type: commerce_subscription
          entity_field: billing_schedule
          plugin_id: field
        created:
          id: created
          table: commerce_subscription
          field: created
          relationship: none
          group_type: group
          admin_label: ''
          label: 'Created On'
          exclude: false
          alter:
            alter_text: false
          element_class: ''
          element_default_classes: false
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: timestamp
          settings:
            date_format: html_date
            custom_date_format: ''
            timezone: ''
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          entity_type: commerce_subscription
          entity_field: created
          plugin_id: field
        starts:
          id: starts
          table: commerce_subscription
          field: starts
          relationship: none
          group_type: group
          admin_label: ''
          label: 'Starts On'
          exclude: false
          alter:
            alter_text: false
          element_class: ''
          element_default_classes: false
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: timestamp
          settings:
            date_format: html_date
            custom_date_format: ''
            timezone: ''
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          entity_type: commerce_subscription
          entity_field: starts
          plugin_id: field
        state:
          id: state
          table: commerce_subscription
          field: state
          relationship: none
          group_type: group
          admin_label: ''
          label: State
          exclude: false
          alter:
            alter_text: false
          element_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: list_default
          settings: {  }
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          entity_type: commerce_subscription
          entity_field: state
          plugin_id: field
        unit_price__number:
          id: unit_price__number
          table: commerce_subscription
          field: unit_price__number
          relationship: none
          group_type: group
          admin_label: ''
          label: Price
          exclude: false
          alter:
            alter_text: false
          element_class: ''
          element_default_classes: false
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: number
          type: commerce_price_default
          settings:
            strip_trailing_zeroes: false
            currency_display: symbol
          group_column: ''
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          entity_type: commerce_subscription
          entity_field: unit_price
          plugin_id: field
        delete_commerce_subscription:
          id: delete_commerce_subscription
          table: commerce_subscription
          field: delete_commerce_subscription
          relationship: none
          group_type: group
          admin_label: ''
          label: Operations
          exclude: false
          alter:
            alter_text: false
          element_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          text: Delete
          output_url_as_text: false
          absolute: false
          entity_type: commerce_subscription
          plugin_id: entity_link_delete
      filters: {  }
      sorts: {  }
      header: {  }
      footer: {  }
      empty:
        area:
          id: area
          table: views
          field: area
          relationship: none
          group_type: group
          admin_label: ''
          empty: true
          tokenize: false
          content:
            value: 'You have no subscriptions.'
            format: full_html
          plugin_id: text
      relationships: {  }
      arguments:
        uid:
          id: uid
          table: commerce_subscription
          field: uid
          relationship: none
          group_type: group
          admin_label: ''
          default_action: 'not found'
          exception:
            value: all
            title_enable: false
            title: All
          title_enable: false
          title: ''
          default_argument_type: fixed
          default_argument_options:
            argument: ''
          default_argument_skip_url: false
          summary_options:
            base_path: ''
            count: true
            items_per_page: 25
            override: false
          summary:
            sort_order: asc
            number_of_records: 0
            format: default_summary
          specify_validation: true
          validate:
            type: commerce_current_user
            fail: 'not found'
          validate_options:
            admin_permission: 'view own commerce_order'
          break_phrase: false
          not: false
          entity_type: commerce_subscription
          entity_field: uid
          plugin_id: numeric
      display_extenders: {  }
      css_class: ''
      title: 'User Subscriptions'
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - url.query_args
        - user
        - user.permissions
      tags: {  }
  page_1:
    display_plugin: page
    id: page_1
    display_title: 'User Subscriptions'
    position: 1
    display_options:
      display_extenders: {  }
      menu:
        type: tab
        title: Subscriptions
        description: ''
        expanded: false
        parent: ''
        weight: 19
        context: '0'
        menu_name: account
      path: user/%user/subscriptions
      display_description: ''
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - url.query_args
        - user
        - user.permissions
      tags: {  }
