<?php

/**
 * @file
 * Contains neibers_seat.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function neibers_seat_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the neibers_seat module.
    case 'help.page.neibers_seat':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The seat of the cabinet.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function neibers_seat_theme() {
  return [
    'neibers_seat' => [
      'render element' => 'elements',
      'file' => 'neibers_seat.page.inc',
      'template' => 'neibers-seat',
    ],
    'neibers_seat_content_add_list' => [
      'render element' => 'content',
      'variables' => ['content' => NULL],
      'file' => 'neibers_seat.page.inc',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function neibers_seat_theme_suggestions_neibers_seat(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#neibers_seat'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'neibers_seat__' . $sanitized_view_mode;
  $suggestions[] = 'neibers_seat__' . $entity->bundle();
  $suggestions[] = 'neibers_seat__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'neibers_seat__' . $entity->id();
  $suggestions[] = 'neibers_seat__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}