<?php

/**
 * @file
 * Contains neibers_category.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function neibers_category_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the neibers_category module.
    case 'help.page.neibers_category':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The category for product.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function neibers_category_theme() {
  $theme = [];
  $theme['neibers_category'] = [
    'render element' => 'elements',
    'file' => 'neibers_category.page.inc',
    'template' => 'neibers_category',
  ];
  $theme['neibers_category_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'neibers_category.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function neibers_category_theme_suggestions_neibers_category(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#neibers_category'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'neibers_category__' . $sanitized_view_mode;
  $suggestions[] = 'neibers_category__' . $entity->bundle();
  $suggestions[] = 'neibers_category__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'neibers_category__' . $entity->id();
  $suggestions[] = 'neibers_category__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
