<?php

/**
 * @file
 * Contains idc_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function idc_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the idc_core module.
    case 'help.page.idc_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The base core module for idc.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_toolbar().
 */
function idc_core_toolbar() {
  $items['idc_core'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('NIDC'),
      '#url' => Url::fromRoute("idc_core.admin"),
      '#attributes' => [
        'title' => t('Nidc menu'),
        'class' => ['toolbar-icon', 'toolbar-icon-idc'],
        'data-drupal-subtree' => '',
      ],
    ],
    'tray' => [
      '#heading' => t('Administer Nidc'),
    ],
    '#weight' => 100,
    '#attached' => [
      'library' => [
        'idc_core/drupal.idc_core',
      ],
    ],
  ];

  return $items;
}