<?php

/**
 * @file
 * Contains cabinet.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cabinet_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cabinet module.
    case 'help.page.cabinet':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The hardware cabinet for idc industrial.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function cabinet_theme() {
  $theme = [];
  $theme['cabinet'] = [
    'render element' => 'elements',
    'file' => 'cabinet.page.inc',
    'template' => 'cabinet',
  ];
  $theme['cabinet_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'cabinet.page.inc',
  ];
  $theme['seat'] = [
    'render element' => 'elements',
    'file' => 'seat.page.inc',
    'template' => 'seat',
  ];
  $theme['seat_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'seat.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function cabinet_theme_suggestions_cabinet(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#cabinet'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'cabinet__' . $sanitized_view_mode;
  $suggestions[] = 'cabinet__' . $entity->bundle();
  $suggestions[] = 'cabinet__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'cabinet__' . $entity->id();
  $suggestions[] = 'cabinet__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function cabinet_theme_suggestions_seat(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#seat'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'seat__' . $sanitized_view_mode;
  $suggestions[] = 'seat__' . $entity->bundle();
  $suggestions[] = 'seat__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'seat__' . $entity->id();
  $suggestions[] = 'seat__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
