<?php

/**
 * @file
 * Contains translation.module.
 */

/**
 * Implements hook_locale_translation_projects_alter().
 */
function neibers_translation_locale_translation_projects_alter(&$projects) {
  $modules = [
    'commerce',
    'commerce_recurring',
    'drupal',
    'features',
    'inline_entity_form',
    'migrate_tools',
    'rules',
    'token',
  ];
  $path = drupal_get_path('module', 'neibers_translation');
  foreach ($modules as $module) {
    $projects[$module]['info']['interface translation project'] = 'neibers_translation';
    $projects[$module]['info']['interface translation server pattern'] = $path . '/translations/' . $module . '.%language.po';
  }
}
