<?php

/**
 * @file
 * Contains neibers_commerce_recurring.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function neibers_recurring_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the neibers_commerce_recurring module.
    case 'help.page.neibers_recurring':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Commerce recurring plus.') . '</p>';
      return $output;

    default:
  }
}
