<?php

/**
 * @file
 * Contains neibers_room.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function neibers_room_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the neibers_room module.
    case 'help.page.neibers_room':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The machine room of store computer equipments.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function neibers_room_theme() {
  return [
    'room' => [
      'render element' => 'elements',
      'file' => 'neibers_room.page.inc',
      'template' => 'neibers_room',
      ],
    'room_content_add_list' => [
      'render element' => 'content',
      'variables' => ['content' => NULL],
      'file' => 'neibers_room.page.inc',
    ],
  ];
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function neibers_room_theme_suggestions_room(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#room'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'neibers_room__' . $sanitized_view_mode;
  $suggestions[] = 'neibers_room__' . $entity->bundle();
  $suggestions[] = 'neibers_room__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'neibers_room__' . $entity->id();
  $suggestions[] = 'neibers_room__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
