eabax_workflow.field_control:
  type: mapping
  mapping:
    view:
      type: boolean
    update:
      type: boolean
    value:
      type: ignore
    status_setting:
      type: string

entity_status.state:
  type: workflows.state
  mapping:
    fields_control:
      type: sequence
      label: 'Fields access'
      sequence:
        type: eabax_workflow.field_control

entity_status.transition:
  type: workflows.transition
  mapping:
    conditions:
      type: sequence
      label: 'Conditions'
      sequence:
        - type: transition.conditions

field.storage_settings.entity_status:
  type: mapping
  label: 'Entity status'
  mapping:
    workflow:
      type: string
      label: 'Workflow value'
    workflow_type:
      type: string
      label: 'Workflow type value'
      
transition.conditions:
  type: mapping
  label: "Conditions"
  mapping:
    id:
      type: string
      label: 'Plugin ID'
    uuid:
      type: string
      label: 'UUID'
    condition_id:
      type: string
      label: 'Condition Plugin ID'

action.configuration.entity:wst:*:
  type: action_configuration_default
  label: 'Entity action'
  mapping:
    workflow:
      type: string
      label: 'Workflow'
    field:
      type: string
      label: 'Field'
    transition:
      type: string
      label: 'Transition'
