<?php

/**
 * @file
 * Contains neibers_ip.module.
 */

use Drupal\commerce_order\Entity\OrderType;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\neibers_ip\Entity\IPType;

/**
 * Implements hook_help().
 */
function neibers_ip_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the neibers_ip module.
    case 'help.page.neibers_ip':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Uip') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function neibers_ip_theme() {
  $theme = [];
  $theme['neibers_ip'] = [
    'render element' => 'elements',
    'file' => 'neibers_ip.page.inc',
  ];
  $theme['neibers_ip_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'neibers_ip.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function neibers_ip_theme_suggestions_neibers_ip(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#neibers_ip'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'neibers_ip__' . $sanitized_view_mode;
  $suggestions[] = 'neibers_ip__' . $entity->bundle();
  $suggestions[] = 'neibers_ip__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'neibers_ip__' . $entity->id();
  $suggestions[] = 'neibers_ip__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function neibers_ip_entity_extra_field_info() {
  $extra = [];
  foreach (OrderType::loadMultiple() as $bundle) {
    $extra['commerce_order'][$bundle->id()]['display']['ips'] = [
      'label' => t('ips'),
      'description' => t('The ips belongs to current order.'),
      'weight' => 0,
    ];
  }
  foreach (IPType::loadMultiple() as $bundle) {
    $extra['neibers_ip'][$bundle->id()]['display']['order_ips'] = [
      'label' => t('Order ips'),
      'description' => t('The ips belongs to current order.'),
      'weight' => 20,
    ];
  }
  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function neibers_ip_commerce_order_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('ips')) {
    $build['ips'] = \Drupal::formBuilder()->getForm('\Drupal\neibers_ip\Form\IPOrderBkForm', $entity, $display);
  }
}
