<?php

/**
 * @file
 * Contains fitting.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fitting_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fitting module.
    case 'help.page.fitting':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The fittings of a machine.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function fitting_theme() {
  $theme = [];
  $theme['fitting'] = [
    'render element' => 'elements',
    'file' => 'fitting.page.inc',
    'template' => 'fitting',
  ];
  $theme['fitting_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'fitting.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function fitting_theme_suggestions_fitting(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#fitting'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'fitting__' . $sanitized_view_mode;
  $suggestions[] = 'fitting__' . $entity->bundle();
  $suggestions[] = 'fitting__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'fitting__' . $entity->id();
  $suggestions[] = 'fitting__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
