<?php

/**
 * @file
 * Contains idc.module.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\ip\Entity\IPType;
use Drupal\ip\Entity\IPTypeInterface;

/**
 * Implements hook_help().
 */
function idc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the idc module.
    case 'help.page.idc':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The industry of idc.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function idc_theme() {
  return [
    'idc' => [
      'render element' => 'children',
    ],
  ];
}


/**
 * Implements hook_block_access().
 */
function idc_block_access(Block $block, $operation, AccountInterface $account) {
  if ($operation == 'view') {
    $plugin_id = $block->getPluginId();
    if (in_array($plugin_id, ['local_actions_block'])) {
      $route_name = \Drupal::routeMatch()->getRouteName();
      $hide_on = [
        'entity.ip.canonical',
      ];
      if (in_array($route_name, $hide_on)) {
        return AccessResult::forbidden();
      }
    }
  }

  return AccessResult::neutral();
}

