<?php

/**
 * @file
 * Contains idc.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\ip\Entity\IPType;
use Drupal\ip\Entity\IPTypeInterface;

/**
 * Implements hook_help().
 */
function idc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the idc module.
    case 'help.page.idc':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The industry of idc.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function idc_theme() {
  return [
    'idc' => [
      'render element' => 'children',
    ],
  ];
}

//function idc_entity_extra_field_info() {
//  $extra = [];
//  foreach (IPType::loadMultiple() as $bundle) {
//    $extra['ip_field_data'][$bundle->id()]['display']['order_ips'] = [
//      'label' => t('Order ips'),
//      'description' => t('The ips belongs to current order.'),
//      'weight' => 0,
//    ];
//  }
//
//  return $extra;
//}